server:
    port : 8080

spring:
    application:
        name : springboot-hibernate-oracle-example
        
    datasource:
        url : jdbc:oracle:thin:@localhost:1521:orcl
        username : system
        password : password
        driver-class-name : oracle.jdbc.OracleDriver
        hikari:
            connection-timeout : 60000
            maximum-pool-size : 5

    jpa:
        database-platform : org.hibernate.dialect.Oracle10gDialect
        hibernate.ddl-auto : none
        generate-ddl : false
        properties:
            hibernate:
                hbm2ddl:
                    auto : update

logging:
    level:
        org:
            hibernate:
                SQL : error